---
- name: Set Name Servers
  hosts: cisco
  gather_facts: no
   
  tasks:
    - name: Change Name Servers
      cisco.ios.ios_facts:
        commands: 
        - ip name-server 8.8.8.8
        - ip name-server 8.8.4.4